#!/usr/bin/env node
const process              = require("process");
const JSBuild              = require("./js_build");
const CSSBuild             = require("./css_build");
const vfl                  = require("./vfl");

process.chdir(__dirname);

console.log("cdbuild");
console.log("Build tool for CustoDesk assets");
console.log();

const PARTS = {
    css: CSSBuild,
    js: JSBuild
};

const DEBUG = process.argv[2].toLowerCase() == "debug";

for (const part in PARTS)
{
    console.log(`Building '${part}'...`);
    PARTS[part](DEBUG);
}